export function City() {
  return (
    <>
      <option value="city">city</option>
      <option value="18">Guwahati</option>
      <option value="73">Aurangabad</option>
      <option value="75">Baramati</option>
      <option value="77">Bhiwandi</option>
      <option value="85">Dhule</option>
      <option value="86">Dombivli</option>
      <option value="87">Durgapur</option>
      <option value="93">Jalgaon</option>
      <option value="99">Kolhapur</option>
      <option value="100">Latur</option>
      <option value="108">Malkapur</option>
      <option value="118">Miraj</option>
      <option value="122">Mumbai</option>
      <option value="124">Nagpur</option>
      <option value="131">Nashik</option>
      <option value="132">Navi Mumbai</option>
      <option value="142">Panvel</option>
      <option value="154">Pune</option>
      <option value="187">Thane</option>
      <option value="218">Allahabad</option>
      <option value="231">Bulandshahr</option>
      <option value="242">Fatehabad</option>
      <option value="249">Ghaziabad</option>
      <option value="251">Gorakhpur</option>
      <option value="253">Hamirpur</option>
      <option value="261">Jhansi</option>
      <option value="263">Kanpur</option>
      <option value="266">Kota</option>
      <option value="269">Lakhimpur</option>
      <option value="275">Lucknow</option>
      <option value="278">Meerut</option>
      <option value="283">Muzaffarnagar</option>
      <option value="285">Najibabad</option>
      <option value="293">Noida</option>
      <option value="366">Varanasi</option>
      <option value="373">Ahmedabad</option>
      <option value="397">Gandhinagar</option>
      <option value="401">Jamnagar</option>
      <option value="438">Rajkot</option>
      <option value="449">Surat</option>
      <option value="459">Vadodara</option>
      <option value="460">Valsad</option>
      <option value="461">Vapi</option>
      <option value="505">Hyderabad</option>
      <option value="543">Nandyal</option>
      <option value="567">Rajahmundry</option>
      <option value="579">Sangareddy</option>
      <option value="593">Tirupati</option>
      <option value="599">Vijayawada</option>
      <option value="601">Visakhapatnam</option>
      <option value="604">Warangal</option>
      <option value="623">Bangalore</option>
      <option value="625">Belgaum</option>
      <option value="654">Kota</option>
      <option value="673">Mysore</option>
      <option value="751">Kochi</option>
      <option value="753">Kollam</option>
      <option value="780">Punalur</option>
      <option value="786">Trivandrum</option>
      <option value="788">Thrissur</option>
      <option value="804">Barrackpur</option>
      <option value="813">Durgapur</option>
      <option value="816">Howrah</option>
      <option value="820">Jhargram</option>
      <option value="824">Kolkata</option>
      <option value="848">Siliguri</option>
      <option value="863">Udaipur</option>
      <option value="876">Bilaspur</option>
      <option value="899">Raipur</option>
      <option value="927">Kapurthala</option>
      <option value="936">Ludhiana</option>
      <option value="941">Moga</option>
      <option value="942">Mohali</option>
      <option value="971">Zirakpur</option>
      <option value="976">Ajmer</option>
      <option value="988">Bikaner</option>
      <option value="994">Hanumangarh</option>
      <option value="996">Jaipur</option>
      <option value="1002">Jodhpur</option>
      <option value="1003">Kota</option>
      <option value="1069">Suratgarh</option>
      <option value="1074">Udaipur</option>
      <option value="1081">Mapusa</option>
      <option value="1093">Haridwar</option>
      <option value="1102">Nainital</option>
      <option value="1104">Pithoragarh</option>
      <option value="1107">Roorkee</option>
      <option value="1118">Araria</option>
      <option value="1123">Aurangabad</option>
      <option value="1134">Begusarai</option>
      <option value="1138">Bhagalpur</option>
      <option value="1148">Darbhanga</option>
      <option value="1155">Gaya</option>
      <option value="1177">Madhubani</option>
      <option value="1197">Nawada</option>
      <option value="1199">Patna</option>
      <option value="1216">Siwan</option>
      <option value="1237">Dhanbad</option>
      <option value="1246">Hazaribag</option>
      <option value="1260">Ranchi</option>
      <option value="1282">Bhubaneswar</option>
      <option value="1288">Cuttack</option>
      <option value="1331">Chennai</option>
      <option value="1333">Coimbatore</option>
      <option value="1337">Dindigul</option>
      <option value="1344">Kanchipuram</option>
      <option value="1350">Madurai</option>
      <option value="1370">Panruti</option>
      <option value="1424">Tiruchirappalli</option>
      <option value="1448">Vellore</option>
      <option value="1457">Bilaspur</option>
      <option value="1461">Hamirpur</option>
      <option value="1465">Shimla</option>
      <option value="1472">Bahadurgarh</option>
      <option value="1480">Faridabad</option>
      <option value="1481">Fatehabad</option>
      <option value="1485">Gurgaon</option>
      <option value="1487">Hisar</option>
      <option value="1495">Karnal</option>
      <option value="1501">Narnaul</option>
      <option value="1504">Panchkula</option>
      <option value="1505">Panipat</option>
      <option value="1511">Rohtak</option>
      <option value="1515">Sirsa</option>
      <option value="1517">Sonipat</option>
      <option value="1521">Yamunanagar</option>
      <option value="1527">Bhopal</option>
      <option value="1537">Fatehabad</option>
      <option value="1540">Gwalior</option>
      <option value="1541">Harda</option>
      <option value="1542">Indore</option>
      <option value="1544">Jabalpur</option>
      <option value="1560">Mandsaur</option>
      <option value="1598">Satna</option>
      <option value="1624">Delhi</option>
      <option value="1625">New Delhi</option>
      <option value="1626">Chandigarh</option>
      <option value="1631">Kohima</option>
      <option value="1656">Mira Bhayandar</option>
      <option value="1686">Jammu</option>
      <option value="1687">Kathua</option>
      <option value="1692">Srinagar</option>
      <option value="1710">Greater Mumbai</option>
      <option value="1712">Vasai Virar</option>
      <option value="1728">Hyderabad</option>
      <option value="1751">Sangareddy</option>
      <option value="1758">Warangal</option>
      <option value="1767">Thiruvananthapuram</option>
      <option value="1771">Bengaluru</option>
      <option value="1772">Belagavi</option>
      <option value="1835">Srinagar</option>
    </>
  );
}
export function Court() {
  return (
    <>
      <option value="court">Court</option>
      <option value="35">Allahabad High Court (Lucknow Bench)</option>
      <option value="5">Bombay High Court</option>
      <option value="36">Bombay High Court (Aurangabad Bench)</option>
      <option value="37">Bombay High Court (Nagpur Bench)</option>
      <option value="38">Bombay High Court (Panaji Bench)</option>
      <option value="39">Calcutta High Court</option>
      <option value="40">Calcutta High Court (Port Blair Bench)</option>
      <option value="4">Chhattisgarh High Court</option>
      <option value="6">Delhi High Court</option>
      <option value="16">Gauhati High Court</option>
      <option value="47">Gauhati High Court (Aizawl Bench)</option>
      <option value="48">Gauhati High Court (Itanagar Bench)</option>
      <option value="49">Gauhati High Court (Kohima Bench)</option>
      <option value="7">Gujarat High Court</option>
      <option value="8">Himachal Pradesh High Court</option>
      <option value="2">Hyderabad High Court</option>
      <option value="50">Jammu and Kashmir High Court</option>
      <option value="10">Jharkhand High Court</option>
      <option value="11">Karnataka High Court</option>
      <option value="45">Karnataka High Court (Dharwad Bench)</option>
      <option value="46">Karnataka High Court (Gulbarga Bench)</option>
      <option value="12">Kerala High Court</option>
      <option value="13">Madhya Pradesh High Court</option>
      <option value="43">Madhya Pradesh High Court (Gwalior Bench)</option>
      <option value="44">Madhya Pradesh High Court (Indore Bench)</option>
      <option value="21">Madras High Court</option>
      <option value="42">Madras High Court (Madurai Bench)</option>
      <option value="14">Manipur High Court</option>
      <option value="15">Meghalaya High Court</option>
      <option value="17">Odisha High Court</option>
      <option value="3">Patna High Court</option>
      <option value="18">Punjab and Haryana High Court</option>
      <option value="19">Rajasthan High Court</option>
      <option value="41">Rajasthan High Court (Jaipur Bench)</option>
      <option value="20">Sikkim High Court</option>
      <option value="28">Supreme Court of India</option>
      <option value="22">Tripura High Court</option>
      <option value="24">Uttarakhand High Court</option>
    </>
  );
}
